CREATE TABLE "TJOEUNIT"."MEMBER" 
(	"ID" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
"PASSWORD" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
"NICKNAME" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
"NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"GENDER" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
"JUMIN" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
"TELEPHONE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"AGE" NUMBER(*,0) NOT NULL ENABLE, 
"EMAIL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
"POSTCODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
"ADDRESS" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
"DETAILADDRESS" VARCHAR2(3000 BYTE) NOT NULL ENABLE, 
"EXTRAADDRESS" VARCHAR2(3000 BYTE), 
 CONSTRAINT "MEMBER_PK" PRIMARY KEY ("ID")
USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM"  ENABLE
) SEGMENT CREATION IMMEDIATE 
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE "SYSTEM" ;

delete from MEMBER;
 
SELECT * FROM member;
commit;